### ISSUE TITLE
Support in C++ Comment

### ISSUE THREAD

**Issue by liwenjun2721** [howcasperwhat/comment-formula#1]
Hello! Would it be possible to extend this to C++ comment?

**Comment by howcasperwhat** [comment]
Thank you for reporting this issue. I have published a new version (v0.2.0) of the extension that should resolve this problem. Please update to the latest version and let me know if you still encounter any issues. You can see the details of the new version in the [release notes](https://github.com/howcasperwhat/comment-formula/releases/tag/v0.2.0).
