### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by liliaoyuan** [howcasperwhat/comment-formula#2]
Hi it's a definitely awesome program!

For me, I think it's a little small size with"partial" mode.
Can I customized the font size?  If so, how can I implement it.

**Comment by howcasperwhat** [comment]
Hey, thanks for your feedback! Could you send me a screenshot of the font size issue in 'partial' mode? I'll take a look and see if I can improve it in the future.

**Comment by liliaoyuan** [comment]
> Hey, thanks for your feedback! Could you send me a screenshot of the font size issue in 'partial' mode? I'll take a look and see if I can improve it in the future.

I change the highligh effective with underline, this is much better.(used to be line-through)
